
envName: null
profile: null

default:
  destination:
    server: https://kubernetes.default.svc  
  project:    
    roles: |
      - name: read-only
        description: Read-only privileges within project
        policies:
        - p, proj:{{ $.curProjName }}:read-only, applications, get, {{ $.curProjName }}/*, allow
      - name: ci-role
        description: Role to allow CICD pipeline to sync apps within project
        policies:
        - p, proj:{{ $.curProjName }}:ci-role, applications, sync, {{ $.curProjName }}/*, allow        
        
global:
  default:
    app:
      enableAutoSync: true
      autoSyncPrune: true
      source:
        targetRevision: HEAD          